import json
import random
import sys
from pathlib import Path

# === 1. Dynamically locate your root API folder ===
# This file is at: D:\test\football\API\stream-scraping\core\team_data.py
# The API root is three levels up.
API_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(API_ROOT))

# === 2. Import your existing season paths ===
try:
    from config import get_season_paths
    # Force the relative path from config.py to be absolute
    TEAMS_DIR = API_ROOT / get_season_paths()["teams_dir"]
except ImportError:
    # Safe fallback if config cannot be loaded
    TEAMS_DIR = API_ROOT / "data" / "2025-2026" / "teams"
    
# === Random logo placeholders ===
LOGOS = [
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/aves.png",
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/benfica.png",
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/braga.png",
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/fcboavista.png",
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/maritimo.png",
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/porto.png",
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/sporting.png",
    "https://raw.githubusercontent.com/gowrapavan/Goal4u/main/public/assets/img/tv-logo/valencia.png",
]

TEAM_DATA = []

def random_logo():
    return random.choice(LOGOS)

def load_team_data():
    """
    Reads the local JSON files generated by workers/fetch_teams.py
    instead of making network calls to GitHub.
    """
    global TEAM_DATA
    if TEAM_DATA:
        return TEAM_DATA
        
    if not TEAMS_DIR.exists():
        print(f"⚠️ Local teams directory not found at: {TEAMS_DIR}")
        return TEAM_DATA

    # Loop through all competition subfolders (e.g., PL, WC, CL)
    for comp_dir in TEAMS_DIR.iterdir():
        if not comp_dir.is_dir():
            continue
            
        # Loop through all {team_id}.json files in the competition folder
        for file_path in comp_dir.glob("*.json"):
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    payload = json.load(f)
                    
                    # safe_write wraps the data, so we must extract the "data" key
                    team = payload.get("data")
                    if team:
                        TEAM_DATA.append(team)
            except Exception as e:
                print(f"⚠️ Failed to load local team file {file_path.name}: {e}")

    return TEAM_DATA

def find_team_crest(team_name):
    """Find crest URL for given team name safely, protecting against nulls."""
    if not team_name:
        return random_logo()
        
    team_name_low = str(team_name).lower()
    
    # 1. First pass: Check for exact matches
    for team in TEAM_DATA:
        # Using .get('key') or "" ensures we don't crash if a field is explicitly null
        team_full = (team.get("name") or "").lower()
        team_short = (team.get("shortName") or "").lower()
        
        if team_name_low in team_full or team_name_low in team_short:
            return team.get("crest") or random_logo()
            
    # 2. Second pass: Check if the first word of the team matches
    parts = team_name_low.split()
    if parts:
        first_word = parts[0]
        for team in TEAM_DATA:
            team_full = (team.get("name") or "").lower()
            if first_word in team_full and first_word != "":
                return team.get("crest") or random_logo()
                
    # 3. Fallback
    return random_logo()